services:
  db:
    image: postgres:15-alpine
    container_name: odoo-db
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGDATA=/var/lib/postgresql/data/pgdata
      # Add these environment variables to configure authentication
      - POSTGRES_HOST_AUTH_METHOD=md5
      - POSTGRES_INITDB_ARGS=--auth-host=md5 --auth-local=md5
    volumes:
      - ${DB_VOLUME_PATH:-./data/db}:/var/lib/postgresql/data/pgdata:z
    networks:
      - odoo-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  odoo:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        - BUILD_ENV=${BUILD_ENV:-prod}
    container_name: odoo-app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "${ODOO_PORT:-8069}:8069"
      - "${ODOO_LONGPOLL_PORT:-8072}:8072"
    environment:
      # Database connection parameters
      - DB_HOST=db
      - DB_PORT=5432
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      # Odoo configuration parameters
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - BUILD_ENV=${BUILD_ENV:-prod}
      - INIT_MODULES=${INIT_MODULES:-base,web}
      - WITHOUT_DEMO=${WITHOUT_DEMO:-all}
      - WORKERS=${WORKERS:-2}
      - CRON_WORKERS=${CRON_WORKERS:-1}
      - MEMORY_SOFT=${MEMORY_SOFT:-2147483648}
      - MEMORY_HARD=${MEMORY_HARD:-2684354560}
      - CPU_LIMIT=${CPU_LIMIT:-60}
      - REAL_LIMIT=${REAL_LIMIT:-120}
      - LIST_DB=${LIST_DB:-False}
      - LOG_LEVEL=${LOG_LEVEL:-info}
    volumes:
      - ${ODOO_DATA_PATH:-./data/odoo}:/var/lib/odoo:z
      - ${ODOO_ADDONS_PATH:-./addons}:/mnt/extra-addons:z
      - ./logs/odoo:/var/log/odoo:z
    restart: always
    networks:
      - odoo-network

  nginx:
    image: nginx:alpine
    container_name: odoo-nginx
    depends_on:
      - odoo
    ports:
      - "${HTTP_PORT:-80}:80"
      - "${HTTPS_PORT:-443}:443"
    volumes:
      - ../config/nginx.conf:/etc/nginx/templates/default.conf.template:ro
      - ${NGINX_LOG_PATH:-./logs/nginx}:/var/log/nginx
      - ${SSL_CERT_PATH:-./data/nginx/ssl}:/etc/nginx/ssl:ro
    environment:
      - DOMAIN=${DOMAIN:-localhost}
      - NGINX_HOST=${DOMAIN:-localhost}
      - NGINX_PORT=80
    restart: always
    networks:
      - odoo-network

networks:
  odoo-network:
    driver: bridge